spring:
  jpa:
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 20
        jdbc.fetch_size: 20
        show_sql: true

  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:

  h2.console.enabled: true

  data.rest:
    base-path: /api
    default-page-size: 20
    return-body-on-create: true

  cache:
    cache-names: restaurants
    caffeine.spec: maximumSize=10000,expireAfterAccess=24h

server.servlet.encoding:
  charset: UTF-8
  enabled: true
  force: true

logging:
  level:
    root: warn
    com.restaurant_voting: debug
    org.springframework.security.web.FilterChainProxy: debug

springdoc.swagger-ui.path: /